// ***TASK CONSTANTS***
// FETCH ALL
export const TASK_FETCH_ALL_REQUEST = "TASK_FETCH_ALL_REQUEST";
export const TASK_FETCH_ALL_SUCCESS = "TASK_FETCH_ALL_SUCCESS";
export const TASK_FETCH_ALL_FAIL = "TASK_FETCH_ALL_FAIL";
// CREATE NEW
export const TASK_CREATE_NEW_TASK_REQUEST = "TASK_CREATE_NEW_TASK_REQUEST";
export const TASK_CREATE_NEW_TASK_SUCCESS = "TASK_CREATE_NEW_TASK_SUCCESS";
export const TASK_CREATE_NEW_TASK_FAIL = "TASK_CREATE_NEW_TASK_FAIL";
// UPDATE ORDER
export const TASK_UPDATE_TASKS_ORDER_REQUEST =
    "TASK_UPDATE_TASKS_ORDER_REQUEST";
export const TASK_UPDATE_TASKS_ORDER_SUCCESS =
    "TASK_UPDATE_TASKS_ORDER_SUCCESS";
export const TASK_UPDATE_TASKS_ORDER_FAIL = "TASK_UPDATE_TASKS_ORDER_FAIL";
// DELETE TASK
export const TASK_DELETE_TASK_REQUEST = "TASK_DELETE_TASK_REQUEST";
export const TASK_DELETE_TASK_SUCCESS = "TASK_DELETE_TASK_SUCCESS";
export const TASK_DELETE_TASK_FAIL = "TASK_DELETE_TASK_FAIL";
